### ISSUE TITLE
Aggregations destroyed after update of SQLite plugin

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [splitbrain/dokuwiki-plugin-data#236] opened 2023-06-29 10:11 UTC
After SQLite update, the aggregations of the Structured Data Plugin are partially destroyed. Some entries are duplicated, and some columns are empty.

Best regards
Juergen

**Comment by splitbrain** [comment] 2023-06-29 10:13
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Please also describe what steps you took to analyze the issue and what (failed) attempts you made to fix the problem yourself.

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by Juergen-aus-Zuendorf** [comment] 2023-06-29 13:05
**Error description:**

For example:
I have an aggregation of our company employees with the following syntax:
```
---- datatable ----
cols       : Anrede, %pageid%, Kurzzeichen, Abteilung_person-abt, Telefon, Mobil, Email_mail
header     : Anr.,   Name,     Kurzz.     , Abt.,                 Tel.,    Mobil, Email
filter     : %pageid%~personal:personalstammdaten:*
sort       : %pageid%
dynfilters : 1
----
```
The aggregation brings as extract this result:
![image](https://github.com/splitbrain/dokuwiki-plugin-data/assets/1800472/b9b1e6d1-b13e-4877-9baa-ebae3510f6a4)
As you can see, from line 2 onwards, the entries are duplicated.

Here is the definition for the item in line 2:
```
---- dataentry personendaten ----
Anrede                : Hr. # 
Nachname              : Gerold # 
Vorname               : Udo # 
Kurzzeichen           :  # 
Bereich_person-bers   : Verwaltung # 
Abteilung_person-abts : MW, MWS # 
Unterbereichs         : ML # 
Arbeitsplatz          :  # 
```
The error seems to be dependent on the type aliases, if they allow multiple values. If I delete the second value for "Abteilung_person-abts" the aggregation is correct.

Our release is "2022-07-31a Igor". There are no error logs.

**Attempts to fix the problem:**
I have deactivated and reactivated the data plugin, but nothing has changed. I haven't yet dared to delete the plugin and reinstall it because I'm afraid of losing the definition of the type aliases in the process.

Best regards
Juergen

**Comment by jnv** [comment] 2023-07-12 21:03
I second this issue. However, it seems the issue is really with the sqlite plugin and not with the data plugin. My workaround was downgrading the sqlite plugin to version [2022-11-29](https://github.com/cosmocode/sqlite/releases/tag/2022-11-29). I noticed that between the releases there were some attempts to switch to sqlite's native group_concat. Perhaps there are some leftovers after reverting?

**Comment by splitbrain** [comment] 2023-07-13 06:08
@jnv can you give the devel branch a try?

**Comment by jnv** [comment] 2023-07-13 06:48
@splitbrain I'm running a fork of this plugin with numeric sorting (#204), but from a quick glance I should be able to rebase that on top of devel. I'll give it a try, thanks!

**Comment by splitbrain** [comment] 2023-12-20 15:05
Closing this, since no further feedback has been given.

**Closed by splitbrain** 2023-12-20 15:05 UTC
